### ISSUE TITLE
Indexing of directories containing awk scripts hangs if Plugin AWK Support is enabled

### ISSUE THREAD

**Issue by gunterze** [xonixx/intellij-awk#103]
Environment:
IntelliJ IDEA 2021.2.2 (Ultimate Edition) Build #IU-212.5284.40,
AWK Support 0.2.2
Linux  5.11.0-37-generic #41~20.04.2-Ubuntu SMP x86_64 GNU/Linux

Corresponding issue opened at JetBrains:
https://intellij-support.jetbrains.com/hc/en-us/requests/3548926

**Comment by xonixx** [comment]
Issue is fixed. Fix will be included in upcoming release.
