### ISSUE TITLE
v0.2.5.1 does nothing in CLion 2021.3.1

### ISSUE THREAD

**Issue by tamboril** [xonixx/intellij-awk#116]
I got a notification that support for .awk became available and just installed it in CLion and restarted, but there's absolutely nothing highlighted in my .awk file.  It seems like no features of the plugin are doing anything.

**Comment by xonixx** [comment]
@tamboril Thank you for your report, I’ll try to investigate soon. Just in case, what operating system do you use?

**Comment by xonixx** [comment]
@tamboril Could you please also check two more things:

1. Please check if the plug-in AWK Support is enabled - just in case? 
2. Could you please check the file association settings for *.awk. Can it be it associated with text files, for example?

**Comment by tamboril** [comment]
It was the file association.  I guess I had forced it to 'text' a long time ago .
So it works!  Thanks.

**Comment by xonixx** [comment]
Nice, glad that it helped!
