### ISSUE TITLE
Add support for 2022.1

### ISSUE THREAD

**Issue by PawelLipski** [xonixx/intellij-awk#122]
![image](https://user-images.githubusercontent.com/3383210/163973200-a1859316-4a89-4f0a-a6fc-016ab685540f.png)

://

**Comment by xonixx** [comment]
Hey @PawelLipski thanks for your report. I will try to update as soon as I can. This is a bit hard now since I'm in Ukraine.

**Comment by xonixx** [comment]
Released.

**Comment by PawelLipski** [comment]
Gr8, just downloaded :)
