### ISSUE TITLE
Incorrect message: Parameter '...' is never used 

### ISSUE THREAD

**Issue by rabestro** [xonixx/intellij-awk#169]
![image](https://user-images.githubusercontent.com/52966251/219953126-26d20c71-f037-4576-a716-a4a075937981.png)

**Comment by xonixx** [comment]
Hey @rabestro. Thank you for the bug report.

**Comment by rabestro** [comment]
> Hey @rabestro. Thank you for the bug report.

I'm happy to help in any way. I actively use your program and it helps me a lot.
