### ISSUE TITLE
Wrong inspection: Delete unused function 

### ISSUE THREAD

**Issue by rabestro** [xonixx/intellij-awk#174]
```awk
BEGIN {FS=""}
{
    print reverse()
}

function reverse(   i,result) {
    for (i = NF; i ; --i) {
        result = result $i
    }
    return result
}
```

<img width="529" alt="image" src="https://user-images.githubusercontent.com/52966251/225858510-b8508910-2a31-4bd0-9c89-396fd1304bcb.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/52966251/225858994-ab964707-f687-4025-a4f3-902f513a7750.png">

**Comment by xonixx** [comment]
Hey @rabestro, thank for your bug report!

I can't reproduce this when the file is a part of a project, but I can see this issue when the file is opened from outside of a project. So I think this relates to #155.

Could you please confirm?

**Comment by rabestro** [comment]
> Hey @rabestro, thank you for your bug report!
> 
> I can't reproduce this when the file is a part of a project, but I can see this issue when the file is opened from outside of a project. So I think this relates to #155.
> 
> Could you please confirm?

<img width="837" alt="image" src="https://user-images.githubusercontent.com/52966251/226176196-a1942961-fcb5-44c8-9614-5a8ffa7c1968.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/52966251/226176268-6230da86-4609-4faf-a791-140f31a8907b.png">
