### ISSUE TITLE
Support for 2023.3

### ISSUE THREAD

**Issue by PawelLipski** [xonixx/intellij-awk#208]
Thanks for your continued work! could you provide support for 2023.3? I can actually recommend the machinery that we've got in our plugin that does the version bumping (semi)automatically: https://github.com/VirtusLab/git-machete-intellij-plugin/blob/develop/.circleci/config.yml#L255 + https://github.com/VirtusLab/git-machete-intellij-plugin/blob/develop/buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateIntellijVersions.kt

**Comment by xonixx** [comment]
Thank you for this report! I'll release the update as soon as I can.

**Comment by xonixx** [comment]
I've released the update to Jetbrains, but it takes some time for them to approve.
