### ISSUE TITLE
Not compatible with the version of your running IDE (PhpStorm 2024.1 EAP)

### ISSUE THREAD

**Issue by jpotter23** [xonixx/intellij-awk#211]
I've lost syntax highlighting suport for awk language for the past few months waiting for the plugin to be updated. I hope this is something that can be remedied as I use AWK everywhere and hate jumping back into VIM for editing if possible. Thanks!

**Comment by xonixx** [comment]
Oh, this is unfortunate. I'll try to release an update asap.

**Comment by jpotter23** [comment]
tyvm your contribution to the community is thoroughly appreciated here!

**Comment by xonixx** [comment]
The thing is that I was targetting the latest release always, which is 2023.3.5 in the case of PhpStorm: https://www.jetbrains.com/phpstorm/. 
I need to understand how can I anticipate the new versions that people use (like EAP) earlier.

**Comment by xonixx** [comment]
Plugin update is uploaded. Waiting for a confirmation by JetBrains.

@jakubkierzkowski Thank you. Yes, this should solve the issue, but I'm trying a simler approach. Basically, I've set the `untilBuild.set('999.*')`. Let's see if this helps long-term.
![image](https://github.com/xonixx/intellij-awk/assets/11706893/5b184789-67d6-4e56-9bc3-2e821b0d1d04)

**Comment by xonixx** [comment]
FYI: New version is approved.

**Comment by xonixx** [comment]
I hope this is solved now. Closing.
