### ISSUE TITLE
False positive warning "Function ... is never used" 

### ISSUE THREAD

**Issue by rabestro** [xonixx/intellij-awk#214]
<img width="942" alt="image" src="https://github.com/xonixx/intellij-awk/assets/52966251/60084a70-516d-4785-8c24-c8b577cf15e2">

**Comment by xonixx** [comment]
Yeah, this is GAWK-specific.

**Comment by rabestro** [comment]
> Yeah, this is GAWK-specific.

Does original AWK support function references?

<img width="1220" alt="image" src="https://github.com/xonixx/intellij-awk/assets/52966251/78f153a9-f670-4d0a-8be1-cc7921ff711d">

**Comment by rabestro** [comment]
For the reference there are the code snippets:
https://github.com/rabestro/exercism-solutions-awk

**Comment by xonixx** [comment]
I've implemented. 
Cases covered:
### case 1
```awk
BEGIN { a = "fname"; @a() }
function fname() {} # will not be reported as unused
```

### case 2
```awk
BEGIN { b("fname") }
function b(f) { @f() }
function fname() {} # will not be reported as unused
```

### case 3
```awk
BEGIN { PROCINFO["sorted_in"] = "fname" }
function fname() {} # will not be reported as unused
```

But in all cases the presence of a string with function name is needed. That means the example of your second screenshot is not covered. @rabestro 

Also false-positives are possible, that is a link will be created between a string and a function even in absence of an actual call:
```awk
BEGIN { a = "fname" }
function fname() {} # will not be reported as unused
```
I think this is the best we can do.

This will be included in the upcoming release.
